package lifeinsurancesystem_payments;

import static org.testng.Assert.assertTrue;


import java.io.FileInputStream;

import Newa_generic_utility.Baseclass;
import Newa_generic_utility.ExcelUtlity;
import Newa_generic_utility.FileUtlity;
import Newa_generic_utility.WebActionUtility;

import java.time.Duration;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;

import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.WorkbookFactory;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;
import org.testng.Assert;
import org.testng.Reporter;
import org.testng.annotations.Listeners;
import org.testng.annotations.Test;

import Newa_LIMS_Object_Repository.CreateNomineePage;
import Newa_LIMS_Object_Repository.HomePage;
import Newa_LIMS_Object_Repository.LoginPage;
import Newa_LIMS_Object_Repository.NomineeInformationPage;
import Newa_LIMS_Object_Repository.VerifyNomineePage;

//@Listeners(Newa_generic_utility.ListnerImplimentation.class)
public class CreatenomineeandverifyTest extends Baseclass {
	@Test (groups= {"SmokeTest"})
	public void addnominee() throws Throwable
	{
          // welcome
		//Vinayak
		String TEST_SCRIPT_EXCEL_FILE_PATH = fLib.getFilePathFromPropertiesFile("testScriptdatafilePath");
		String Exp_msg = "New Nominee ADDED";		

		/* Read Test Data from Excel File */
		String CLIENTID = elib.getDataFromExcelBasedTestId(TEST_SCRIPT_EXCEL_FILE_PATH, "lims", "tc_02", "Client_id");
		String CLIENTNAME = elib.getDataFromExcelBasedTestId(TEST_SCRIPT_EXCEL_FILE_PATH, "lims", "tc_02",
				"Client_name");
		String SEX = elib.getDataFromExcelBasedTestId(TEST_SCRIPT_EXCEL_FILE_PATH, "lims", "tc_02", "Sex");
		String BIRTHDATE = elib.getDataFromExcelBasedTestId(TEST_SCRIPT_EXCEL_FILE_PATH, "lims", "tc_02", "Birth_Date");
		String NID = elib.getDataFromExcelBasedTestId(TEST_SCRIPT_EXCEL_FILE_PATH, "lims", "tc_02", "Nid");
		String RELATIONSHIP = elib.getDataFromExcelBasedTestId(TEST_SCRIPT_EXCEL_FILE_PATH, "lims", "tc_02",
				"Relationship");
		String PRIORITY = elib.getDataFromExcelBasedTestId(TEST_SCRIPT_EXCEL_FILE_PATH, "lims", "tc_02", "Priority");
		String PHONENUMBER = elib.getDataFromExcelBasedTestId(TEST_SCRIPT_EXCEL_FILE_PATH, "lims", "tc_02",
				"Phone"); 
		
		/* Navigate Through nominee */
		HomePage home = new HomePage(driver);
		home.nomineebtn();
		
		/* Navigate Through Addnominee */
		NomineeInformationPage nip = new NomineeInformationPage(driver);
		nip.addnomineebtn();    

		/* get the autogenerated nominee id */
		CreateNomineePage CNP = new CreateNomineePage(driver);
		String Exp_Nomineeid = CNP.NomineeAutoid();
		System.out.println(Exp_Nomineeid); 

		/* Create Nominee enter all the details */
		CreateNomineePage create = new CreateNomineePage(driver);
		create.Nominee(CLIENTID, CLIENTNAME, SEX, BIRTHDATE, NID, RELATIONSHIP, PRIORITY, PHONENUMBER);
		
		/* varify Nominee added */
		VerifyNomineePage vnp = new VerifyNomineePage(driver);
		String Act_msg = vnp.verifynominee();
		
		
		Assert.assertTrue(Act_msg.contains(Exp_msg),Exp_msg+"  "+"Nominee is not added Successfully Not Verified----->Fail");
		Reporter.log(Exp_msg+"  "+"Nominee is added Successfully Verified----->Pass",true);
	

		/* navigate through nominee */
		HomePage hp = new HomePage(driver);
		hp.nomineebtn();

		/* Verify Nominee added */		
		VerifyNomineePage VNP = new VerifyNomineePage(driver);
		ArrayList<String>l1=new ArrayList<>();
		List<WebElement> all_id = VNP.Nomineeid();
		for (WebElement we: all_id) 
		{
			String Act_Nomineeid = we.getAttribute("innerHTML");
			l1.add(Act_Nomineeid);
		}
		assertTrue(l1.contains(Exp_Nomineeid),Exp_Nomineeid+" "+"Nominee id is not Verify & is not displayed in nominee table----->Fail");
		Reporter.log(Exp_Nomineeid+"  "+"Nominee id is Verified & is  Displayed in nominee table----->Pass",true);
		// completed.
		//Test Case Executed Successfully.
	}
}
